---

# For use with pre-commit.
# See usage instructions at https://pre-commit.com

-   id: sanitize-env-files
    name: Sanitize .env files and create example versions
    entry: ./sanitize-env-hook.sh
    language: script
    files: '^\.env(\..+)?$'  # Updated regex to match .env and .env.<environment>