---

# For use with pre-commit.
# See usage instructions at https://pre-commit.com

-   id: sanitize-env-files
    name: sanitize .env files and create example versions
    entry: ./pre-commit-wrapper.py
    language: script
    files: '^\.env(\..+)?$'  # Updated regex to match .env and .env.<environment>